Repository Plane-walker/Okeanos, pull requests merged in 2021-12, with the labels that each got.

#5 Generate grpc.
  README.md
  dock/dock.py
  dock/gnn/node_classification.py
  dock/interface/__init__.py
  dock/interface/dci_pb2.py
  dock/interface/dci_pb2_grpc.py
  dock/interface/gogo_pb2.py
  dock/interface/gogo_pb2_grpc.py
  main.py
  protos/bci/bci.proto
  protos/dci/dci.proto
  protos/gogoproto/gogo.proto
  protos/sci/sci.proto
  test/__init__.py
  test/dock/__init__.py
  test/dock/test_gnn.py
Labels: enhancement

#17 Cccp2
  dock/cccp/test_cccp2.py
Labels: good first issue

#18 Doc. Ref #13
  123.md
  ccdp.txt
Labels: good first issue

#16 New File. Ref #13
  cccp.txt
  proto/DCI/cccp.proto
Labels: good first issue

#20 Test merge. Ref #19
  dock/cccp/test_cccp2.py
Labels: good first issue

#21 Completed. Ref #19
  dock/cccp/test_cccp2.py
Labels: good first issue

#27 delete test files. Ref #22
  123.md
  cccp.txt
  ccdp.txt
  dock/cccp/test_cccp2.py
  proto/DCI/cccp.proto
Labels: enhancement

#36 Create Node classification function
  dock/gnn/default_config.yaml
  dock/gnn/graphSAGE.py
  dock/gnn/node_classification.py
  dock/gnn/random_walker.py
  dock/gnn/sequence.py
  dock/util/util.py
Labels: enhancement

#39 Save and load graphSAGE model
  README.md
  dock/gnn/node_classification.py
  dock/netopter/__init__.py
  dock/netopter/default_config.yaml
  dock/netopter/graph_sage.py
  dock/netopter/network_optimizer.py
  dock/netopter/node_classification.py
  dock/netopter/query_info.py
  dock/netopter/random_walker.py
  dock/netopter/sequence.py
  dock/util/__init__.py
  dock/util/util.py
  test/dock/netopter/__init__.py
  test/dock/netopter/test_gnn.py
Labels: enhancement

#41 Create data class for node classification and test file
  .gitignore
  README.md
  dock/netopter/default_config.yaml
  dock/netopter/graph_data.py
  dock/netopter/node_classification.py
  test/dock/netopter/test_gnn.py
  test/dock/netopter/test_node_classification.py
Labels: enhancement

#42 Create node embeding predict function
  dock/netopter/graph_data.py
  dock/netopter/node_classification.py
Labels: enhancement

#46 interface about bci. Ref #44
  protos/bci/bci.proto
Labels: enhancement

#53 Update dci.proto. Ref #24
  README.md
  protos/dci/dci.proto
Labels: enhancement

#55 Add rpc call from BCI to get neighbor's info
  .gitignore
  README.md
  dock/netopter/default_config.yaml
  dock/netopter/graph_data.py
  dock/netopter/network_optimizer.py
  dock/netopter/node_classification.py
  dock/netopter/query_info.py
  test/dock/netopter/test_node_classification.py
Labels: enhancement

#54 Add the NextRoute. Ref #51
  protos/bci/bci.proto
Labels: enhancement

#57 Add the interface about callback. Ref #56
  protos/bci/bci.proto
Labels: enhancement

#58 Define Tx and packagedTx in proto. Ref#47
  dock/interface/dci_pb2.py
  dock/interface/dci_pb2_grpc.py
  protos/dci/dci.proto
Labels: enhancement

#59 Expose next_node in router part. Ref #49
  .gitignore
  dock/router/router.py
  test/dock/router/__init__.py
  test/dock/router/test_router.py
Labels: enhancement

#60 Node representation learning
  dock/netopter/network_optimizer.py
  protos/dci/dci.proto
Labels: enhancement

#61 Finish transmit and callback.
  .gitignore
  dock/router/router.py
Labels: enhancement

#64 Finish the gossip part
  dock/interface/bci_pb2.py
  dock/interface/bci_pb2_grpc.py
  dock/interface/dci_pb2.py
  dock/router/router.py
  protos/bci/bci.proto
  protos/dci/dci.proto
Labels: enhancement

#67 Refactor interface
  dock/dock.py
  dock/netopter/graph_data.py
  dock/netopter/network_optimizer.py
  dock/router/router.py
  interface/__init__.py
  interface/bci/__init__.py
  interface/bci/bci_pb2.py
  interface/bci/bci_pb2_grpc.py
  interface/dci/__init__.py
  interface/dci/dci_pb2.py
  interface/dci/dci_pb2_grpc.py
  interface/gogo_pb2.py
  interface/gogo_pb2_grpc.py
  test/dock/router/test_router.py
Labels: enhancement

#68 Add the server of grpc
  dock/dock.py
  dock/router/router.py
  interface/dci/dci_pb2.py
  interface/dci/dci_pb2_grpc.py
  protos/dci/dci.proto
  test/dock/router/test_router.py
Labels: enhancement

#70 Fix test router bug
  README.md
  dock/__init__.py
  dock/default_config.yaml
  dock/dock.py
  dock/router/__init__.py
  main.py
  test/dock/router/test_router.py
Labels: bug

#75 Add data_chain and add config for Router
  dock/dock.py
  dock/router/default_router_config.yaml
  dock/router/router.py
Labels: bug

#77 Update test case for router
  dock/dock.py
  dock/router/router.py
  test/dock/router/test_router.py
Labels: bug, enhancement
